// lib/iranData.ts



export const provinces = [
  { id: 1, name: "آذربایجان شرقی" },
  { id: 2, name: "آذربایجان غربی" },
  { id: 3, name: "اردبیل" },
  { id: 4, name: "اصفهان" },
  { id: 5, name: "البرز" },
  { id: 6, name: "ایلام" },
  { id: 7, name: "بوشهر" },
  { id: 8, name: "تهران" },
  { id: 9, name: "چهارمحال و بختیاری" },
  { id: 10, name: "خراسان جنوبی" },
  { id: 11, name: "خراسان رضوی" },
  { id: 12, name: "خراسان شمالی" },
  { id: 13, name: "خوزستان" },
  { id: 14, name: "زنجان" },
  { id: 15, name: "سمنان" },
  { id: 16, name: "سیستان و بلوچستان" },
  { id: 17, name: "فارس" },
  { id: 18, name: "قزوین" },
  { id: 19, name: "قم" },
  { id: 20, name: "کردستان" },
  { id: 21, name: "کرمان" },
  { id: 22, name: "کرمانشاه" },
  { id: 23, name: "کهگیلویه و بویراحمد" },
  { id: 24, name: "گلستان" },
  { id: 25, name: "گیلان" },
  { id: 26, name: "لرستان" },
  { id: 27, name: "مازندران" },
  { id: 28, name: "مرکزی" },
  { id: 29, name: "هرمزگان" },
  { id: 30, name: "همدان" },
  { id: 31, name: "یزد" },
];

export const cities = [
  // ==================== آذربایجان شرقی ====================
  { id: 1, name: "تبریز", province_id: 1 },
  { id: 2, name: "مراغه", province_id: 1 },
  { id: 3, name: "مرند", province_id: 1 },
  { id: 75, name: "اهر", province_id: 1 },
  { id: 76, name: "بناب", province_id: 1 },
  { id: 77, name: "سراب", province_id: 1 },
  { id: 78, name: "شبستر", province_id: 1 },
  { id: 79, name: "عجب‌شیر", province_id: 1 },
  { id: 80, name: "کلیبر", province_id: 1 },
  { id: 81, name: "هشترود", province_id: 1 },
  { id: 82, name: "ملکان", province_id: 1 },
  { id: 83, name: "میانه", province_id: 1 },
  { id: 84, name: "ورزقان", province_id: 1 },
  { id: 85, name: "هریس", province_id: 1 },
  { id: 86, name: "جلفا", province_id: 1 },
  { id: 87, name: "اسکو", province_id: 1 },
  { id: 88, name: "آذرشهر", province_id: 1 },
  { id: 89, name: "قره‌آغاج", province_id: 1 },
  { id: 90, name: "کلیدار", province_id: 1 },
  { id: 91, name: "بستان‌آباد", province_id: 1 },

  // ==================== آذربایجان غربی ====================
  { id: 4, name: "ارومیه", province_id: 2 },
  { id: 5, name: "خوی", province_id: 2 },
  { id: 6, name: "مهاباد", province_id: 2 },
  { id: 92, name: "بوکان", province_id: 2 },
  { id: 93, name: "سلماس", province_id: 2 },
  { id: 94, name: "نقده", province_id: 2 },
  { id: 95, name: "پیرانشهر", province_id: 2 },
  { id: 96, name: "میاندوآب", province_id: 2 },
  { id: 97, name: "شاهین‌دژ", province_id: 2 },
  { id: 98, name: "تکاب", province_id: 2 },
  { id: 99, name: "سیه‌چشمه", province_id: 2 },
  { id: 100, name: "ماکو", province_id: 2 },
  { id: 101, name: "شوط", province_id: 2 },
  { id: 102, name: "پلدشت", province_id: 2 },
  { id: 103, name: "قره‌ضیاءالدین", province_id: 2 },
  { id: 104, name: "اشنویه", province_id: 2 },
  { id: 105, name: "سردشت", province_id: 2 },
  { id: 106, name: "باروق", province_id: 2 },
  { id: 107, name: "چهاربرج", province_id: 2 },

  // ==================== اردبیل ====================
  { id: 7, name: "اردبیل", province_id: 3 },
  { id: 8, name: "پارس‌آباد", province_id: 3 },
  { id: 9, name: "مشگین‌شهر", province_id: 3 },
  { id: 108, name: "بیله‌سوار", province_id: 3 },
  { id: 109, name: "خلخال", province_id: 3 },
  { id: 110, name: "گیوی", province_id: 3 },
  { id: 111, name: "نیر", province_id: 3 },
  { id: 112, name: "نمین", province_id: 3 },
  { id: 113, name: "اصلاندوز", province_id: 3 },
  { id: 114, name: "انگوت", province_id: 3 },
  { id: 115, name: "سرعین", province_id: 3 },

  // ==================== اصفهان ====================
  { id: 10, name: "اصفهان", province_id: 4 },
  { id: 11, name: "کاشان", province_id: 4 },
  { id: 12, name: "نجف‌آباد", province_id: 4 },
  { id: 116, name: "خمینی‌شهر", province_id: 4 },
  { id: 117, name: "شاهین‌شهر", province_id: 4 },
  { id: 118, name: "زرین‌شهر", province_id: 4 },
  { id: 119, name: "مبارکه", province_id: 4 },
  { id: 120, name: "آران و بیدگل", province_id: 4 },
  { id: 121, name: "نطنز", province_id: 4 },
  { id: 122, name: "اردستان", province_id: 4 },
  { id: 123, name: "نایین", province_id: 4 },
  { id: 124, name: "خور", province_id: 4 },
  { id: 125, name: "گلپایگان", province_id: 4 },
  { id: 126, name: "خوانسار", province_id: 4 },
  { id: 127, name: "شهرضا", province_id: 4 },
  { id: 128, name: "سمیرم", province_id: 4 },
  { id: 129, name: "دهاقان", province_id: 4 },
  { id: 130, name: "داران", province_id: 4 },
  { id: 131, name: "فریدون‌شهر", province_id: 4 },
  { id: 132, name: "چادگان", province_id: 4 },
  { id: 133, name: "تیران", province_id: 4 },
  { id: 134, name: "بوئین", province_id: 4 },
  { id: 135, name: "دولت‌آباد", province_id: 4 },
  { id: 136, name: "هرند", province_id: 4 },
  { id: 137, name: "نیک‌آباد", province_id: 4 },
  { id: 138, name: "کوهپایه", province_id: 4 },
  { id: 139, name: "ورزنه", province_id: 4 },
  { id: 140, name: "سجزی", province_id: 4 },
  { id: 141, name: "میمه", province_id: 4 },
  { id: 142, name: "فولادشهر", province_id: 4 },
  { id: 143, name: "بادرود", province_id: 4 },
  { id: 144, name: "قهدریجان", province_id: 4 },

  // ==================== البرز ====================
  { id: 13, name: "کرج", province_id: 5 },
  { id: 14, name: "فردیس", province_id: 5 },
  { id: 145, name: "نظرآباد", province_id: 5 },
  { id: 146, name: "طالقان", province_id: 5 },
  { id: 147, name: "اشتهارد", province_id: 5 },
  { id: 148, name: "چهارباغ", province_id: 5 },
  { id: 149, name: "ماهدشت", province_id: 5 },
  { id: 150, name: "محمدشهر", province_id: 5 },

  // ==================== ایلام ====================
  { id: 15, name: "ایلام", province_id: 6 },
  { id: 16, name: "دهلران", province_id: 6 },
  { id: 151, name: "ایوان", province_id: 6 },
  { id: 152, name: "آبدانان", province_id: 6 },
  { id: 153, name: "دره‌شهر", province_id: 6 },
  { id: 154, name: "مهران", province_id: 6 },
  { id: 155, name: "بدره", province_id: 6 },
  { id: 156, name: "سرابله", province_id: 6 },
  { id: 157, name: "صالح‌آباد", province_id: 6 },

  // ==================== بوشهر ====================
  { id: 17, name: "بوشهر", province_id: 7 },
  { id: 18, name: "برازجان", province_id: 7 },
  { id: 158, name: "بندر گناوه", province_id: 7 },
  { id: 159, name: "بندر دیر", province_id: 7 },
  { id: 160, name: "بندر دیلم", province_id: 7 },
  { id: 161, name: "بندر کنگان", province_id: 7 },
  { id: 162, name: "بندر عسلویه", province_id: 7 },
  { id: 163, name: "خورموج", province_id: 7 },
  { id: 164, name: "اهرم", province_id: 7 },
  { id: 165, name: "جم", province_id: 7 },
  { id: 166, name: "کاکی", province_id: 7 },
  { id: 167, name: "بوشکان", province_id: 7 },

  // ==================== تهران ====================
  { id: 19, name: "تهران", province_id: 8 },
  { id: 20, name: "اسلامشهر", province_id: 8 },
  { id: 21, name: "شهریار", province_id: 8 },
  { id: 168, name: "رباط‌کریم", province_id: 8 },
  { id: 169, name: "ورامین", province_id: 8 },
  { id: 170, name: "پاکدشت", province_id: 8 },
  { id: 171, name: "دماوند", province_id: 8 },
  { id: 172, name: "فیروزکوه", province_id: 8 },
  { id: 173, name: "ری", province_id: 8 },
  { id: 174, name: "قدس", province_id: 8 },
  { id: 175, name: "ملارد", province_id: 8 },
  { id: 176, name: "پردیس", province_id: 8 },
  { id: 177, name: "قرچک", province_id: 8 },
  { id: 178, name: "پیشوا", province_id: 8 },
  { id: 179, name: "نصیرشهر", province_id: 8 },
  { id: 180, name: "اندیشه", province_id: 8 },
  { id: 181, name: "بومهن", province_id: 8 },
  { id: 182, name: "پرند", province_id: 8 },
  { id: 183, name: "لواسان", province_id: 8 },
  { id: 184, name: "رودهن", province_id: 8 },

  // ==================== چهارمحال و بختیاری ====================
  { id: 22, name: "شهرکرد", province_id: 9 },
  { id: 23, name: "بروجن", province_id: 9 },
  { id: 185, name: "فارسان", province_id: 9 },
  { id: 186, name: "اردل", province_id: 9 },
  { id: 187, name: "لردگان", province_id: 9 },
  { id: 188, name: "کیار", province_id: 9 },
  { id: 189, name: "سامان", province_id: 9 },
  { id: 190, name: "بن", province_id: 9 },
  { id: 191, name: "نافچ", province_id: 9 },
  { id: 192, name: "گندمان", province_id: 9 },
  { id: 193, name: "فرخشهر", province_id: 9 },
  { id: 194, name: "شلمزار", province_id: 9 },

  // ==================== خراسان جنوبی ====================
  { id: 24, name: "بیرجند", province_id: 10 },
  { id: 25, name: "قائن", province_id: 10 },
  { id: 195, name: "نهبندان", province_id: 10 },
  { id: 196, name: "سربیشه", province_id: 10 },
  { id: 197, name: "فردوس", province_id: 10 },
  { id: 198, name: "طبس", province_id: 10 },
  { id: 199, name: "بشرویه", province_id: 10 },
  { id: 200, name: "درمیان", province_id: 10 },
  { id: 201, name: "خوسف", province_id: 10 },
  { id: 202, name: "زیرکوه", province_id: 10 },

  // ==================== خراسان رضوی ====================
  { id: 26, name: "مشهد", province_id: 11 },
  { id: 27, name: "نیشابور", province_id: 11 },
  { id: 28, name: "سبزوار", province_id: 11 },
  { id: 203, name: "تربت حیدریه", province_id: 11 },
  { id: 204, name: "تربت جام", province_id: 11 },
  { id: 205, name: "قوچان", province_id: 11 },
  { id: 206, name: "کاشمر", province_id: 11 },
  { id: 207, name: "گناباد", province_id: 11 },
  { id: 208, name: "چناران", province_id: 11 },
  { id: 209, name: "سرخس", province_id: 11 },
  { id: 210, name: "فریمان", province_id: 11 },
  { id: 211, name: "درگز", province_id: 11 },
  { id: 212, name: "خواف", province_id: 11 },
  { id: 213, name: "رشتخوار", province_id: 11 },
  { id: 214, name: "ماهشهر", province_id: 11 },
  { id: 215, name: "باخرز", province_id: 11 },
  { id: 216, name: "داورزن", province_id: 11 },
  { id: 217, name: "جغتای", province_id: 11 },
  { id: 218, name: "بردسکن", province_id: 11 },
  { id: 219, name: "تایباد", province_id: 11 },
  { id: 220, name: "فیروزه", province_id: 11 },
  { id: 221, name: "زبرخان", province_id: 11 },
  { id: 222, name: "ششتمد", province_id: 11 },
  { id: 223, name: "میان جلگه", province_id: 11 },
  { id: 224, name: "گلبهار", province_id: 11 },

  // ==================== خراسان شمالی ====================
  { id: 29, name: "بجنورد", province_id: 12 },
  { id: 30, name: "شیروان", province_id: 12 },
  { id: 225, name: "اسفراین", province_id: 12 },
  { id: 226, name: "جاجرم", province_id: 12 },
  { id: 227, name: "مانه و سملقان", province_id: 12 },
  { id: 228, name: "راز و جرگلان", province_id: 12 },
  { id: 229, name: "فاروج", province_id: 12 },
  { id: 230, name: "گرمه", province_id: 12 },

  // ==================== خوزستان ====================
  { id: 31, name: "اهواز", province_id: 13 },
  { id: 32, name: "آبادان", province_id: 13 },
  { id: 33, name: "دزفول", province_id: 13 },
  { id: 231, name: "خرمشهر", province_id: 13 },
  { id: 232, name: "مسجدسلیمان", province_id: 13 },
  { id: 233, name: "بهبهان", province_id: 13 },
  { id: 234, name: "رامهرمز", province_id: 13 },
  { id: 235, name: "شوشتر", province_id: 13 },
  { id: 236, name: "اندیمشک", province_id: 13 },
  { id: 237, name: "شوش", province_id: 13 },
  { id: 238, name: "ایذه", province_id: 13 },
  { id: 239, name: "باغملک", province_id: 13 },
  { id: 240, name: "هندیجان", province_id: 13 },
  { id: 241, name: "لالی", province_id: 13 },
  { id: 242, name: "گتوند", province_id: 13 },
  { id: 243, name: "رامشیر", province_id: 13 },
  { id: 244, name: "امیدیه", province_id: 13 },
  { id: 245, name: "هویزه", province_id: 13 },
  { id: 246, name: "بندر ماهشهر", province_id: 13 },
  { id: 247, name: "شادگان", province_id: 13 },
  { id: 248, name: "کارون", province_id: 13 },
  { id: 249, name: "حمیدیه", province_id: 13 },
  { id: 250, name: "سوسنگرد", province_id: 13 },

  // ==================== زنجان ====================
  { id: 34, name: "زنجان", province_id: 14 },
  { id: 35, name: "ابهر", province_id: 14 },
  { id: 251, name: "خرمدره", province_id: 14 },
  { id: 252, name: "ماهنشان", province_id: 14 },
  { id: 253, name: "طارم", province_id: 14 },
  { id: 254, name: "ایجرود", province_id: 14 },
  { id: 255, name: "سلطانیه", province_id: 14 },

  // ==================== سمنان ====================
  { id: 36, name: "سمنان", province_id: 15 },
  { id: 37, name: "شاهرود", province_id: 15 },
  { id: 256, name: "دامغان", province_id: 15 },
  { id: 257, name: "گرمسار", province_id: 15 },
  { id: 258, name: "مهدی‌شهر", province_id: 15 },
  { id: 259, name: "ایوانکی", province_id: 15 },
  { id: 260, name: "بسطام", province_id: 15 },
  { id: 261, name: "میامی", province_id: 15 },
  { id: 262, name: "کلاته خیج", province_id: 15 },

  // ==================== سیستان و بلوچستان ====================
  { id: 38, name: "زاهدان", province_id: 16 },
  { id: 39, name: "زابل", province_id: 16 },
  { id: 40, name: "چابهار", province_id: 16 },
  { id: 263, name: "ایرانشهر", province_id: 16 },
  { id: 264, name: "سراوان", province_id: 16 },
  { id: 265, name: "خاش", province_id: 16 },
  { id: 266, name: "نیکشهر", province_id: 16 },
  { id: 267, name: "کنارک", province_id: 16 },
  { id: 268, name: "قصرقند", province_id: 16 },
  { id: 269, name: "مهرستان", province_id: 16 },
  { id: 270, name: "سرباز", province_id: 16 },
  { id: 271, name: "دلگان", province_id: 16 },
  { id: 272, name: "زهک", province_id: 16 },
  { id: 273, name: "هیرمند", province_id: 16 },
  { id: 274, name: "بمپور", province_id: 16 },
  { id: 275, name: "راسک", province_id: 16 },
  { id: 276, name: "فنوج", province_id: 16 },

  // ==================== فارس ====================
  { id: 41, name: "شیراز", province_id: 17 },
  { id: 42, name: "مرودشت", province_id: 17 },
  { id: 43, name: "جهرم", province_id: 17 },
  { id: 277, name: "فسا", province_id: 17 },
  { id: 278, name: "کازرون", province_id: 17 },
  { id: 279, name: "لارستان", province_id: 17 },
  { id: 280, name: "آباده", province_id: 17 },
  { id: 281, name: "داراب", province_id: 17 },
  { id: 282, name: "اقلید", province_id: 17 },
  { id: 283, name: "نیریز", province_id: 17 },
  { id: 284, name: "سپیدان", province_id: 17 },
  { id: 285, name: "لامرد", province_id: 17 },
  { id: 286, name: "استهبان", province_id: 17 },
  { id: 287, name: "ممسنی", province_id: 17 },
  { id: 288, name: "رستم", province_id: 17 },
  { id: 289, name: "زرقان", province_id: 17 },
  { id: 290, name: "خرامه", province_id: 17 },
  { id: 291, name: "بیضا", province_id: 17 },
  { id: 292, name: "خنج", province_id: 17 },
  { id: 293, name: "فراشبند", province_id: 17 },
  { id: 294, name: "قیر و کارزین", province_id: 17 },
  { id: 295, name: "جویم", province_id: 17 },
  { id: 296, name: "سروستان", province_id: 17 },
  { id: 297, name: "کوار", province_id: 17 },
  { id: 298, name: "پاسارگاد", province_id: 17 },
  { id: 299, name: "بوانات", province_id: 17 },
  { id: 300, name: "خرمبید", province_id: 17 },
  { id: 301, name: "ارسنجان", province_id: 17 },

  // ==================== قزوین ====================
  { id: 44, name: "قزوین", province_id: 18 },
  { id: 45, name: "الوند", province_id: 18 },
  { id: 302, name: "تاکستان", province_id: 18 },
  { id: 303, name: "بوئین زهرا", province_id: 18 },
  { id: 304, name: "آبیک", province_id: 18 },
  { id: 305, name: "محمدیه", province_id: 18 },

  // ==================== قم ====================
  { id: 46, name: "قم", province_id: 19 },
  { id: 306, name: "جعفریه", province_id: 19 },
  { id: 307, name: "دستجرد", province_id: 19 },

  // ==================== کردستان ====================
  { id: 47, name: "سنندج", province_id: 20 },
  { id: 48, name: "سقز", province_id: 20 },
  { id: 49, name: "مریوان", province_id: 20 },
  { id: 308, name: "بانه", province_id: 20 },
  { id: 309, name: "قروه", province_id: 20 },
  { id: 310, name: "دیواندره", province_id: 20 },
  { id: 311, name: "بیجار", province_id: 20 },
  { id: 312, name: "کامیاران", province_id: 20 },
  { id: 313, name: "دهگلان", province_id: 20 },
  { id: 314, name: "سروآباد", province_id: 20 },

  // ==================== کرمان ====================
  { id: 50, name: "کرمان", province_id: 21 },
  { id: 51, name: "سیرجان", province_id: 21 },
  { id: 52, name: "رفسنجان", province_id: 21 },
  { id: 315, name: "جیرفت", province_id: 21 },
  { id: 316, name: "بم", province_id: 21 },
  { id: 317, name: "زرند", province_id: 21 },
  { id: 318, name: "کهنوج", province_id: 21 },
  { id: 319, name: "بافت", province_id: 21 },
  { id: 320, name: "سیرجان", province_id: 21 }, // تکراری؟ قبلاً هست
  { id: 321, name: "شهداد", province_id: 21 },
  { id: 322, name: "عنبرآباد", province_id: 21 },
  { id: 323, name: "راور", province_id: 21 },
  { id: 324, name: "منوجان", province_id: 21 },
  { id: 325, name: "نرماشیر", province_id: 21 },
  { id: 326, name: "فهرج", province_id: 21 },
  { id: 327, name: "ریگان", province_id: 21 },
  { id: 328, name: "بردسیر", province_id: 21 },
  { id: 329, name: "قلعه گنج", province_id: 21 },

  // ==================== کرمانشاه ====================
  { id: 53, name: "کرمانشاه", province_id: 22 },
  { id: 54, name: "اسلام‌آباد غرب", province_id: 22 },
  { id: 330, name: "هرسین", province_id: 22 },
  { id: 331, name: "کنگاور", province_id: 22 },
  { id: 332, name: "صحنه", province_id: 22 },
  { id: 333, name: "پاوه", province_id: 22 },
  { id: 334, name: "سنقر", province_id: 22 },
  { id: 335, name: "قصرشیرین", province_id: 22 },
  { id: 336, name: "روانسر", province_id: 22 },
  { id: 337, name: "ثلاث باباجانی", province_id: 22 },
  { id: 338, name: "دالاهو", province_id: 22 },
  { id: 339, name: "گواور", province_id: 22 },

  // ==================== کهگیلویه و بویراحمد ====================
  { id: 55, name: "یاسوج", province_id: 23 },
  { id: 56, name: "دوگنبدان", province_id: 23 },
  { id: 340, name: "دهدشت", province_id: 23 },
  { id: 341, name: "سی سخت", province_id: 23 },
  { id: 342, name: "لنده", province_id: 23 },
  { id: 343, name: "باشت", province_id: 23 },
  { id: 344, name: "چرام", province_id: 23 },
  { id: 345, name: "مارگون", province_id: 23 },

  // ==================== گلستان ====================
  { id: 57, name: "گرگان", province_id: 24 },
  { id: 58, name: "گنبد کاووس", province_id: 24 },
  { id: 346, name: "علی‌آباد کتول", province_id: 24 },
  { id: 347, name: "کردکوی", province_id: 24 },
  { id: 348, name: "بندر ترکمن", province_id: 24 },
  { id: 349, name: "آزادشهر", province_id: 24 },
  { id: 350, name: "رامیان", province_id: 24 },
  { id: 351, name: "مینودشت", province_id: 24 },
  { id: 352, name: "کلاله", province_id: 24 },
  { id: 353, name: "مراوه تپه", province_id: 24 },
  { id: 354, name: "گمیش تپه", province_id: 24 },
  { id: 355, name: "اینچه برون", province_id: 24 },

  // ==================== گیلان ====================
  { id: 59, name: "رشت", province_id: 25 },
  { id: 60, name: "انزلی", province_id: 25 },
  { id: 61, name: "لاهیجان", province_id: 25 },
  { id: 356, name: "تالش", province_id: 25 },
  { id: 357, name: "فومن", province_id: 25 },
  { id: 358, name: "صومعه سرا", province_id: 25 },
  { id: 359, name: "آستارا", province_id: 25 },
  { id: 360, name: "آستانه اشرفیه", province_id: 25 },
  { id: 361, name: "رودسر", province_id: 25 },
  { id: 362, name: "رودبار", province_id: 25 },
  { id: 363, name: "ماسال", province_id: 25 },
  { id: 364, name: "شفت", province_id: 25 },
  { id: 365, name: "رضوانشهر", province_id: 25 },
  { id: 366, name: "سیاهکل", province_id: 25 },
  { id: 367, name: "املش", province_id: 25 },

  // ==================== لرستان ====================
  { id: 62, name: "خرم‌آباد", province_id: 26 },
  { id: 63, name: "بروجرد", province_id: 26 },
  { id: 368, name: "دورود", province_id: 26 },
  { id: 369, name: "الیگودرز", province_id: 26 },
  { id: 370, name: "کوهدشت", province_id: 26 },
  { id: 371, name: "ازنا", province_id: 26 },
  { id: 372, name: "پلدختر", province_id: 26 },
  { id: 373, name: "نورآباد", province_id: 26 },
  { id: 374, name: "سلسله", province_id: 26 },
  { id: 375, name: "رومشکان", province_id: 26 },
  { id: 376, name: "چگنی", province_id: 26 },

  // ==================== مازندران ====================
  { id: 64, name: "ساری", province_id: 27 },
  { id: 65, name: "بابل", province_id: 27 },
  { id: 66, name: "آمل", province_id: 27 },
  { id: 377, name: "قائم‌شهر", province_id: 27 },
  { id: 378, name: "بهشهر", province_id: 27 },
  { id: 379, name: "نوشهر", province_id: 27 },
  { id: 380, name: "چالوس", province_id: 27 },
  { id: 381, name: "نور", province_id: 27 },
  { id: 382, name: "تنکابن", province_id: 27 },
  { id: 383, name: "رامسر", province_id: 27 },
  { id: 384, name: "جویبار", province_id: 27 },
  { id: 385, name: "بابلسر", province_id: 27 },
  { id: 386, name: "فریدونکنار", province_id: 27 },
  { id: 387, name: "محمودآباد", province_id: 27 },
  { id: 388, name: "نکا", province_id: 27 },
  { id: 389, name: "سوادکوه", province_id: 27 },
  { id: 390, name: "سوادکوه شمالی", province_id: 27 },
  { id: 391, name: "میاندرود", province_id: 27 },
  { id: 392, name: "گلوگاه", province_id: 27 },

  // ==================== مرکزی ====================
  { id: 67, name: "اراک", province_id: 28 },
  { id: 68, name: "ساوه", province_id: 28 },
  { id: 393, name: "خمین", province_id: 28 },
  { id: 394, name: "محلات", province_id: 28 },
  { id: 395, name: "دلیجان", province_id: 28 },
  { id: 396, name: "تفرش", province_id: 28 },
  { id: 397, name: "فراهان", province_id: 28 },
  { id: 398, name: "شازند", province_id: 28 },
  { id: 399, name: "آشتیان", province_id: 28 },
  { id: 400, name: "زرندیه", province_id: 28 },
  { id: 401, name: "خنداب", province_id: 28 },
  { id: 402, name: "کمیجان", province_id: 28 },

  // ==================== هرمزگان ====================
  { id: 69, name: "بندرعباس", province_id: 29 },
  { id: 70, name: "میناب", province_id: 29 },
  { id: 403, name: "بندر لنگه", province_id: 29 },
  { id: 404, name: "جاسک", province_id: 29 },
  { id: 405, name: "قشم", province_id: 29 },
  { id: 406, name: "بستک", province_id: 29 },
  { id: 407, name: "حاجی‌آباد", province_id: 29 },
  { id: 408, name: "دهبارز", province_id: 29 },
  { id: 409, name: "کیش", province_id: 29 },
  { id: 410, name: "ابوموسی", province_id: 29 },
  { id: 411, name: "خمیر", province_id: 29 },
  { id: 412, name: "رودان", province_id: 29 },
  { id: 413, name: "سیریک", province_id: 29 },
  { id: 414, name: "بشاگرد", province_id: 29 },
  { id: 415, name: "پارسیان", province_id: 29 },

  // ==================== همدان ====================
  { id: 71, name: "همدان", province_id: 30 },
  { id: 72, name: "ملایر", province_id: 30 },
  { id: 416, name: "نهاوند", province_id: 30 },
  { id: 417, name: "کبودرآهنگ", province_id: 30 },
  { id: 418, name: "اسدآباد", province_id: 30 },
  { id: 419, name: "تویسرکان", province_id: 30 },
  { id: 420, name: "رزن", province_id: 30 },
  { id: 421, name: "بهار", province_id: 30 },
  { id: 422, name: "فامنین", province_id: 30 },
  { id: 423, name: "قروه درجزین", province_id: 30 },

  // ==================== یزد ====================
  { id: 73, name: "یزد", province_id: 31 },
  { id: 74, name: "میبد", province_id: 31 },
  { id: 424, name: "اردکان", province_id: 31 },
  { id: 425, name: "بافق", province_id: 31 },
  { id: 426, name: "ابرکوه", province_id: 31 },
  { id: 427, name: "تفت", province_id: 31 },
  { id: 428, name: "مهریز", province_id: 31 },
  { id: 429, name: "اشکذر", province_id: 31 },
  { id: 430, name: "خاتم", province_id: 31 },
  { id: 431, name: "بهاباد", province_id: 31 },
  { id: 432, name: "مروست", province_id: 31 },
];

export const getCitiesOfProvince = (provinceId: number) =>
  cities.filter((c) => c.province_id === provinceId);

/**
 * Find a city by its ID across ALL provinces.
 * Used as a fallback when a city ID exists in formData but doesn't belong
 * to the selected province (data integrity issues from legacy submissions).
 */
export const getCityById = (cityId: number) =>
  cities.find((c) => c.id === cityId);
